Homework 5
Katya32/Mortal-Kombat pull request #4
Opened 2021-06-10 19:56 UTC by Katya32

2021-06-10 21:45 UTC, ZarMarathon requested changes

2021-06-10 21:45 UTC, ZarMarathon commented on main.js
> +    subZero.renderHP();
а task 1 где?)

2021-06-11 01:49 UTC, Katya32 commented on main.js
> +    subZero.renderHP();
Добавила)

2021-06-12 12:56 UTC, ZarMarathon approved these changes
аппрув)

2021-06-12 12:56 UTC, ZarMarathon commented on main.js
> +        attack.value = 0;
это бессмысленно)

2021-06-12 18:56 UTC, merged