homework-7
Katya32/Mortal-Kombat pull request #6
Opened 2021-06-15 21:53 UTC by Katya32

Привет)
Не понимаю, что я неправильно делаю с импортом и экспортом...

2021-06-15 23:20 UTC, ZarMarathon requested changes
надо бы доделать разбиение, вынести из main.js всё кроме обработчика формы

2021-06-15 23:20 UTC, ZarMarathon commented on index.html
>      <script src="./logs.js" type="module"></script>
здесь только main подключаем, остальное бессмысленно

2021-06-15 23:20 UTC, ZarMarathon commented on main.js
> +const generateLogs = (type, liuKang, subZero, hp) => {
надо вынести

2021-06-15 23:20 UTC, ZarMarathon commented on main.js
> +const createPlayer = (character) => {  //Функция создает тэги с классами и вставляет их в $player
вот здесь например можно деструктурировать объект, чтобы не обращаться везде через точку)
и лучше функцию вынести, здесь только вызывать)

2021-06-15 23:20 UTC, ZarMarathon commented on main.js
> +import { playerAttack } from './attack';
да всё правильно делаешь, а что, не работает?)

2021-06-16 01:18 UTC, Katya32 commented on main.js
> +import { playerAttack } from './attack';
После импорта функции не доступны, в DevTools пишет ошибку:
GET http://127.0.0.1:5500/showResult net::ERR_ABORTED 404 (Not Found)
main.js:5 GET http://127.0.0.1:5500/reloadButton net::ERR_ABORTED 404 (Not Found)
main.js:6 GET http://127.0.0.1:5500/attack net::ERR_ABORTED 404 (Not Found)
main.js:7 GET http://127.0.0.1:5500/generateLogs net::ERR_ABORTED 404 (Not Found)
main.js:8 GET http://127.0.0.1:5500/createPlayer net::ERR_ABORTED 404 (Not Found)

2021-06-16 13:13 UTC, ZarMarathon approved these changes
нужно .js при импортах дописать (это по той проблеме твоей с модулями), .js можно не писать при сборке вебпаком, а вот нативно js так не умеет)
всё огонь, аппрув)

2021-06-16 13:13 UTC, ZarMarathon commented on generateLogs.js
> +            text = "You didn't press anything";
в дефолтном тоже лучше писать брейк)

2021-06-17 09:33 UTC, merged